
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
        httpserver:
          wiretap: true
      routes:
        - id: rewritepath_gui
          uri: http://host.docker.internal:9000
          predicates:
            - Path=/gui/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: rewritepath_api
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/auth/** , /api/**, /media/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: rewritepath_media
          uri: http://host.docker.internal:8080
          predicates:
            - Path=/media/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
server:
  port: 7777