
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
      httpclient:
        wiretap: true
        httpserver:
          wiretap: true
      routes:
        - id: rewritepath_gui
          uri: http://localhost:9000
          predicates:
            - Path=/gui/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: rewritepath_api
          uri: http://localhost:8080
          predicates:
            - Path=/auth/** , /api/**, /media/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: rewritepath_media
          uri: http://192.168.15.102:8080
          predicates:
            - Path=/media/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}
server:
  port: 7777