
logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
        httpserver:
          wiretap: true
      routes:
        - id: rewritepath_api
          uri: ${API_HOST}
          predicates:
            - Path=/auth/** , /api/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: rewritepath_media
          uri: ${MEDIA_HOST}
          predicates:
            - Path=/media/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: rewritepath_gui
          uri: ${GUI_HOST}
          predicates:
            - Path=/gui/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}

        - id: rewritepath_gui_empty
          uri: ${GUI_HOST}
          predicates:
            - Path=/, /gui, /gui/
          filters:
            - RedirectTo=302, http://${HOST}:${server.port}/gui/

server:
  port: 7777